### ISSUE TITLE
Ignore container when deserializing

### ISSUE THREAD

**Issue by steven-joruk** [media-io/yaserde#74] opened 2020-04-26 19:17 UTC
Hi, I'd like to handle this kind of deserialization:

```xml
<root>
    <ignored>
        <item id="1"/>
        <item id="2"/>
    </ignored>
</root>
```

```rust
#[derive(YaDeserialize)]
#[yaserde(rename = "item")]
struct Item {
    id: String,
}

#[derive(YaDeserialize)]
#[yaserde(rename = "root")]
struct Root {
    /// Some yaserde attribute or custom deserializer to get rid of the `ignored` container.
    items: Vec<Item>,
}
```

Adding a custom deserializer for a newtype doesn't feel much better than just declaring the container type, and there doesn't seem to be an equivalent of serde's `deserialize_with` attribute.

Presuming there isn't a good way of handling this already, would you be interested in a PR to allow users to ignore containers like this?

Thanks.

**Comment by MarcAntoine-Arnaud** [comment] 2020-04-29 16:37
Hello @steven-joruk 

Humm yes you have to declare all levels.
```rust
#[derive(YaDeserialize)]
#[yaserde(rename = "item")]
struct Item {
    #[yaserde(attribute)]
    id: String,
}

#[derive(YaDeserialize)]
#[yaserde(rename = "ignored")]
struct Ignored {
    items: Vec<Item>,
}

#[derive(YaDeserialize)]
#[yaserde(rename = "root")]
struct Root {
    ignored: Ignored,
}
```


It can be very complex to allow to fill with sub-childs.
The invert example is: an XML like
```xml
<root id="0">
    <ignored id="5">
        <item id="1"/>
        <item id="2"/>
    </ignored>
    <other>
        <something id="3" />
    </other>
</root>
```
What can be expected in values from that ...
Which means Serialiser can't reproduce it !

**Comment by steven-joruk** [comment] 2020-04-29 16:53
I might be misunderstanding your example, because it seems clear that only the `item` elements would go in to `Item` structs? There should be no reason for `something` or `other` to be mistaken for anything else.

I was envisioning something like adding an attribute to a field though, like this:

```rust
...
struct Root {
    #[yaserde(container = "ignored")]
    items: Vec<Item>,

    #[yaserde(container = "something")]
    somethings: Vec<Something>,
    ...
```

**Comment by MarcAntoine-Arnaud** [comment] 2020-04-30 07:37
Hi again;
`container` will be `rename` in YaSerDe.
It can works.

**Comment by MarcAntoine-Arnaud** [comment] 2024-08-16 07:38
I think I can close it.

**Closed by MarcAntoine-Arnaud** 2024-08-16 07:38 UTC
